# Generated by Django 3.1.6 on 2021-03-11 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_post2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
    ]
