# Generated by Django 3.1.6 on 2021-03-12 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_post_author'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post2',
        ),
    ]
